# fly.toml app configuration file generated for number-order-us on 2025-04-22T23:43:08+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'number-order-us'
primary_region = 'sjc'

[build]

[env]
  PYTHONUNBUFFERED = "1"
  HEALTH_CHECK_INTERVAL = "300"
  LOG_ROTATION_ENABLED = "true"

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 5000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "off"
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/metrics"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1