# fly.toml app configuration file generated for number-order-us on 2025-04-22T23:43:08+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'number-order-us'
primary_region = 'sjc'

[build]

[[mounts]]
  source = 'data'
  destination = '/data'


[http_service]
  internal_port = 5000
  force_https = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[processes]
  app = "./startup.sh"

[env]
  # Ensure services stay running
  FLY_PROCESS_GROUP = "app"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1